[ 2014-05-20 10:22:05.0081 1672/7ffbb13f4720 agents/Watchdog/Main.cpp:538 ]: Options: { 'analytics_log_user' => 'ralph', 'cleanup_pidfiles' => 'L3RtcC9wYXNzZW5nZXItc3RhbmRhbG9uZS4xYTB1ZHF6L3RlbXBfZGlyX3RvdWNoZXIucGlk', 'default_group' => 'ralph', 'default_python' => 'python', 'default_ruby' => '/usr/local/rvm/gems/ruby-2.1.0/wrappers/ruby', 'default_user' => 'ralph', 'log_level' => '0', 'max_pool_size' => '6', 'passenger_root' => '/tmp/passenger-standalone.1a0udqz/locations.ini', 'passenger_version' => '4.0.42', 'pool_idle_time' => '300', 'prestart_urls' => 'aHR0cDovLzAuMC4wLjA6NDAxMAA=', 'temp_dir' => '/tmp', 'union_station_gateway_address' => 'gateway.unionstationapp.com', 'union_station_gateway_port' => '443', 'user_switching' => 'false', 'web_server_passenger_version' => '4.0.42', 'web_server_pid' => '1671', 'web_server_type' => 'nginx', 'web_server_worker_gid' => '501', 'web_server_worker_uid' => '500' }
[ 2014-05-20 10:22:05.0139 1675/7f5d4ec76720 agents/HelperAgent/Main.cpp:643 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.1671/generation-0/request
[ 2014-05-20 10:22:05.0190 1680/7fba1ed3e720 agents/LoggingAgent/Main.cpp:321 ]: PassengerLoggingAgent online, listening at unix:/tmp/passenger.1.0.1671/generation-0/logging
[ 2014-05-20 10:22:05.0191 1672/7ffbb13f4720 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
2014/05/20 10:22:07 [alert] 1691#0: *3 Cannot stat '/root/rails_projects/catalog.bk/config.ru': Permission denied (errno=13); This error means that the Nginx worker process (PID 1691, running as UID 500) does not have permission to access this file. Please read the manual to learn how to fix this problem: section 'Troubleshooting' -> 'Upon accessing the web app, Nginx reports a "Permission denied" error'; Extra info, client: 127.0.0.1, server: _, request: "HEAD / HTTP/1.1", host: "0.0.0.0"
2014/05/20 10:25:55 [alert] 1691#0: *4 Cannot stat '/root/rails_projects/catalog.bk/config.ru': Permission denied (errno=13); This error means that the Nginx worker process (PID 1691, running as UID 500) does not have permission to access this file. Please read the manual to learn how to fix this problem: section 'Troubleshooting' -> 'Upon accessing the web app, Nginx reports a "Permission denied" error'; Extra info, client: 192.168.1.24, server: _, request: "GET / HTTP/1.1", host: "v1.rwort.co.uk:4010"
2014/05/20 10:25:55 [alert] 1691#0: *5 Cannot stat '/root/rails_projects/catalog.bk/config.ru': Permission denied (errno=13); This error means that the Nginx worker process (PID 1691, running as UID 500) does not have permission to access this file. Please read the manual to learn how to fix this problem: section 'Troubleshooting' -> 'Upon accessing the web app, Nginx reports a "Permission denied" error'; Extra info, client: 192.168.1.24, server: _, request: "GET /favicon.ico HTTP/1.1", host: "v1.rwort.co.uk:4010"
[ 2014-05-20 10:26:25.8701 1680/7fba1ed3e720 agents/LoggingAgent/Main.cpp:289 ]: Caught signal, exiting...
[ 2014-05-20 10:29:25.2223 1340/7fb7259c6720 agents/Watchdog/Main.cpp:538 ]: Options: { 'analytics_log_user' => 'root', 'cleanup_pidfiles' => 'L3RtcC9wYXNzZW5nZXItc3RhbmRhbG9uZS43NzR2Y3kvdGVtcF9kaXJfdG91Y2hlci5waWQ=', 'default_group' => 'root', 'default_python' => 'python', 'default_ruby' => '/usr/local/rvm/gems/ruby-2.1.0/wrappers/ruby', 'default_user' => 'root', 'log_level' => '0', 'max_pool_size' => '6', 'passenger_root' => '/tmp/passenger-standalone.774vcy/locations.ini', 'passenger_version' => '4.0.42', 'pool_idle_time' => '300', 'prestart_urls' => 'aHR0cDovLzAuMC4wLjA6NDAxMAA=', 'temp_dir' => '/tmp', 'union_station_gateway_address' => 'gateway.unionstationapp.com', 'union_station_gateway_port' => '443', 'user_switching' => 'false', 'web_server_passenger_version' => '4.0.42', 'web_server_pid' => '1339', 'web_server_type' => 'nginx', 'web_server_worker_gid' => '0', 'web_server_worker_uid' => '0' }
[ 2014-05-20 10:29:25.2397 1343/7ff016fb6720 agents/HelperAgent/Main.cpp:643 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.1339/generation-0/request
[ 2014-05-20 10:29:25.2445 1351/7fadc605b720 agents/LoggingAgent/Main.cpp:321 ]: PassengerLoggingAgent online, listening at unix:/tmp/passenger.1.0.1339/generation-0/logging
[ 2014-05-20 10:29:25.2446 1340/7fb7259c6720 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
App 1484 stdout: 
[ 2014-05-20 10:29:30.7588 1343/7ff016ebe700 Pool2/SmartSpawner.h:301 ]: Preloader for /root/rails_projects/catalog.bk started on PID 1484, listening on unix:/tmp/passenger.1.0.1339/generation-0/backends/preloader.1484
App 1606 stdout: 
App 1631 stdout: 
App 1640 stdout: 
App 1743 stdout: 
App 1760 stdout: 
[ 2014-05-20 10:37:31.7676 1343/7ff016ebe700 Pool2/Implementation.cpp:1105 ]: Detached process (pid=1640, group=/root/rails_projects/catalog.bk#default) didn't shut down within 1 minute. Forcefully killing it with SIGKILL.
[ 2014-05-20 10:37:37.0333 1343/7ff016ebe700 Pool2/Implementation.cpp:1105 ]: Detached process (pid=1606, group=/root/rails_projects/catalog.bk#default) didn't shut down within 1 minute. Forcefully killing it with SIGKILL.
[ 2014-05-20 10:37:37.4528 1343/7ff016ebe700 Pool2/Implementation.cpp:1105 ]: Detached process (pid=1631, group=/root/rails_projects/catalog.bk#default) didn't shut down within 1 minute. Forcefully killing it with SIGKILL.
[ 2014-05-20 10:49:07.5058 2677/7fb943e56720 agents/Watchdog/Main.cpp:538 ]: Options: { 'analytics_log_user' => 'root', 'cleanup_pidfiles' => 'L3RtcC9wYXNzZW5nZXItc3RhbmRhbG9uZS44dXFqbjgvdGVtcF9kaXJfdG91Y2hlci5waWQ=', 'default_group' => 'root', 'default_python' => 'python', 'default_ruby' => '/usr/local/rvm/gems/ruby-2.1.0/wrappers/ruby', 'default_user' => 'root', 'log_level' => '0', 'max_pool_size' => '6', 'passenger_root' => '/tmp/passenger-standalone.8uqjn8/locations.ini', 'passenger_version' => '4.0.42', 'pool_idle_time' => '300', 'prestart_urls' => 'aHR0cDovLzAuMC4wLjA6NDAxMAA=', 'temp_dir' => '/tmp', 'union_station_gateway_address' => 'gateway.unionstationapp.com', 'union_station_gateway_port' => '443', 'user_switching' => 'false', 'web_server_passenger_version' => '4.0.42', 'web_server_pid' => '2676', 'web_server_type' => 'nginx', 'web_server_worker_gid' => '0', 'web_server_worker_uid' => '0' }
[ 2014-05-20 10:49:07.5125 2680/7f128bb0e720 agents/HelperAgent/Main.cpp:643 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.2676/generation-0/request
[ 2014-05-20 10:49:07.5176 2685/7f02c44e6720 agents/LoggingAgent/Main.cpp:321 ]: PassengerLoggingAgent online, listening at unix:/tmp/passenger.1.0.2676/generation-0/logging
[ 2014-05-20 10:49:07.5178 2677/7fb943e56720 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
App 2815 stdout: 
[ 2014-05-20 10:49:16.6910 2680/7f128ba17700 Pool2/SmartSpawner.h:301 ]: Preloader for /root/rails_projects/catalog.bk started on PID 2815, listening on unix:/tmp/passenger.1.0.2676/generation-0/backends/preloader.2815
App 2940 stdout: 
App 2815 stderr: [ 2014-05-20 10:49:16.8906 2940/0x0000000250d3c0(Worker 1) utils.rb:68 ]: *** Exception RuntimeError in Rack application object (Missing `secret_key_base` for 'production' environment, set this value in `config/secrets.yml`) (process 2940, thread 0x0000000250d3c0(Worker 1)):
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.0/lib/rails/application.rb:440:in `validate_secret_key_config!'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.0/lib/rails/application.rb:195:in `env_config'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.0/lib/rails/engine.rb:510:in `call'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.0/lib/rails/application.rb:144:in `call'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/passenger-4.0.42/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/passenger-4.0.42/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/passenger-4.0.42/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 2815 stderr: 	from /usr/local/rvm/gems/ruby-2.1.0/gems/passenger-4.0.42/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
2014/05/20 10:49:16 [error] 2696#0: *3 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: _, request: "HEAD / HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.2676/generation-0/request:", host: "0.0.0.0"
[ 2014-05-20 12:42:44.2733 2685/7f02c44e6720 agents/LoggingAgent/Main.cpp:289 ]: Caught signal, exiting...
